const W=960,H=600,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),keys={},craft=[],enemyImages=[],bossImages=[];
['small','medium','large'].forEach(n=>{const i=new Image();i.src=`assets/craft/maintenance-craft-${n}.png`;craft.push(i)});
['cocoa-clump','sugar-crystal','burnt-blob','broken-paddle'].forEach(n=>{const i=new Image();i.src=`assets/characters/enemy-${n}.png`;enemyImages.push(i)});
['eternal-clump','seized-gearbox','bloom-beast'].forEach(n=>{const i=new Image();i.src=`assets/characters/boss-${n}.png`;bossImages.push(i)});
let mode='title',s=null,last=performance.now(),musicEnabled=true;
const overlay=document.querySelector('#overlay'),title=document.querySelector('#title'),message=document.querySelector('#message'),stamp=document.querySelector('#stamp'),primary=document.querySelector('#primary'),secondary=document.querySelector('#secondary'),instructions=document.querySelector('#instructions');
const music=document.querySelector('#music'),musicToggle=document.querySelector('#music-toggle');music.volume=.45;
function playMusic(){if(musicEnabled)music.play().catch(()=>{})}
function resume(){mode='playing';overlay.classList.add('hidden');playMusic()}
function reset(){s={p:{x:120,y:300,hp:5,inv:0,power:1},shots:[],enemies:[],drops:[],particles:[],score:0,temp:47,bombs:3,stage:1,wave:0,spawn:30,time:0,shotCd:0,boss:false,msg:'BATCH 01 — ROASTING LINE',msgT:180,shake:0};mode='playing';overlay.classList.add('hidden');musicToggle.classList.remove('hidden');playMusic()}
function exitArcade(){try{music.pause()}catch(_){};if(window.parent&&window.parent!==window)window.parent.postMessage({type:'arcade-game-exit',game:'temper-tantrum'},'*');else location.reload()}
function show(kind){mode=kind;overlay.classList.remove('hidden');secondary.classList.remove('hidden');instructions.classList.add('hidden');if(kind==='paused'){music.pause();stamp.textContent='SHIFT INTERRUPTED';title.textContent='LINE PAUSED';message.textContent='The chocolate is absolutely not getting better while you stand here.';primary.textContent='RESUME SHIFT';primary.onclick=resume;secondary.textContent='EXIT GAME';secondary.onclick=exitArcade}else{stamp.textContent=kind==='victory'?'QUALITY CONTROL PASSED':'INCIDENT REPORT FILED';title.textContent=kind==='victory'?'BATCH SAVED!':'TEMPER TANTRUM!';message.textContent=kind==='victory'?'Three batches survived. Management has taken full credit.':'The line won this round. Try a cooler approach.';primary.textContent='RUN ANOTHER BATCH';primary.onclick=reset;secondary.textContent='MAIN MENU';secondary.onclick=()=>location.reload()}}
primary.onclick=reset;secondary.onclick=()=>location.reload();
musicToggle.onclick=()=>{musicEnabled=!musicEnabled;musicToggle.textContent=musicEnabled?'MUSIC ON':'MUSIC OFF';musicToggle.setAttribute('aria-label',musicEnabled?'Turn music off':'Turn music on');if(musicEnabled)playMusic();else music.pause()};
addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){e.preventDefault();if(mode==='playing')show('paused');else if(mode==='paused')resume()}if(e.code==='KeyB')bomb()});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys[k]=false});document.querySelector('#bomb').onclick=bomb;
canvas.onpointermove=e=>{if(mode!=='playing'||!e.buttons)return;const r=canvas.getBoundingClientRect();s.p.x=(e.clientX-r.left)*W/r.width;s.p.y=(e.clientY-r.top)*H/r.height};
function bomb(){if(mode!=='playing'||!s||s.bombs<1)return;s.bombs--;s.shots=s.shots.filter(b=>!b.enemy);s.shake=18;s.enemies.forEach(e=>e.hp-=e.boss?35:99)}
function update(dt){s.time+=dt;const p=s.p;p.inv=Math.max(0,p.inv-dt);s.shotCd-=dt;s.spawn-=dt;s.msgT-=dt;s.shake=Math.max(0,s.shake-dt);let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0),l=Math.hypot(dx,dy)||1;p.x=Math.max(58,Math.min(W-58,p.x+dx/l*5.2*dt));p.y=Math.max(90,Math.min(H-38,p.y+dy/l*5.2*dt));
if((keys.Space||keys.KeyJ)&&s.shotCd<=0){let hot=Math.max(0,(s.temp-45)/55),counts=[1,2,3,3,4,5,5],count=counts[p.power-1]||5;s.shotCd=Math.max(2.5,10-hot*5-p.power*.65);s.temp+=.13*(1+hot)*dt;for(let i=0;i<count;i++)s.shots.push({x:p.x+58,y:p.y+(i-(count-1)/2)*10,vx:10+hot*4+p.power*.25,vy:(i-(count-1)/2)*(.28+p.power*.035),r:4+hot*2+p.power*.12,d:1+hot*.9+(p.power-1)*.12,color:p.power>=6?'#8ff4ff':hot>.65?'#ff7a37':'#ffe08a'});if(p.power===7)s.shots.push({x:p.x+60,y:p.y,vx:14+hot*4,vy:0,r:7,d:2.5+hot,color:'#ffffff'})}else s.temp-=.025*dt;s.temp=Math.max(8,Math.min(100,s.temp));if(s.temp>=99){p.hp--;p.inv=100;s.temp=42;s.msg='WEAPONS JAMMED — BATCH BURNT';s.msgT=120;if(p.hp<=0)show('gameover')}
if(!s.boss&&s.spawn<=0){s.wave++;s.spawn=Math.max(20,68-s.stage*8);let k=Math.floor(Math.random()*4),upgradeCarrier=s.wave===5||s.wave===10;s.enemies.push({x:W+55,y:90+Math.random()*(H-150),vx:-1.4-s.stage*.3,vy:(Math.random()-.5)*1.2,hp:2+s.stage+Math.min(k,2),max:2+s.stage+Math.min(k,2),r:22+k*2,kind:k,t:0,upgradeCarrier});if(upgradeCarrier){s.msg='WEAPON UPGRADE DETECTED';s.msgT=90}if(s.wave>=12+s.stage*2)spawnBoss()}
s.enemies.forEach(e=>{e.t+=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(!e.boss)e.y+=Math.sin(e.t*.04+e.x)*.65;if(e.boss){e.y=H/2+Math.sin(e.t*.018)*150;if(e.t%55<dt)s.shots.push({x:e.x-e.r,y:e.y,vx:-4.2,vy:(Math.random()-.5)*2.2,r:7,enemy:true,color:'#d8f0ef'})}else if(e.t%90<dt)s.shots.push({x:e.x,y:e.y,vx:-3.5,vy:(p.y-e.y)/180,r:5,enemy:true,color:'#f9b8ce'})});s.shots.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});
s.shots.filter(b=>!b.enemy).forEach(b=>s.enemies.forEach(e=>{if(e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.hp-=b.d||1;b.x=W+200;s.score+=10}}));s.shots.filter(b=>b.enemy).forEach(b=>{if(p.inv<=0&&Math.hypot(b.x-p.x,b.y-p.y)<b.r+18){b.x=-100;p.hp--;p.inv=90;if(p.hp<=0)show('gameover')}});s.enemies.forEach(e=>{if(p.inv<=0&&Math.hypot(e.x-p.x,e.y-p.y)<e.r+22){e.hp=0;p.hp--;p.inv=90;if(p.hp<=0)show('gameover')}});
let dead=s.enemies.filter(e=>e.hp<=0);dead.forEach(e=>{if(e.upgradeCarrier)s.drops.push({x:e.x,y:e.y,kind:'power',t:0});else if(Math.random()<.18)s.drops.push({x:e.x,y:e.y,kind:Math.random()<.65?'cool':'bomb',t:0});if(e.boss){s.boss=false;s.score+=5000;p.power=Math.min(7,p.power+1);s.stage++;s.wave=0;s.spawn=180;if(s.stage>3)show('victory');else{s.msg=`WEAPON LV.${p.power} — BATCH 0${s.stage}`;s.msgT=200}}});s.enemies=s.enemies.filter(e=>e.hp>0&&e.x>-120);s.shots=s.shots.filter(b=>b.x>-80&&b.x<W+80&&b.y>-50&&b.y<H+50);s.drops.forEach(d=>{d.t+=dt;d.x-=1.5*dt;if(Math.hypot(d.x-p.x,d.y-p.y)<28){if(d.kind==='cool')s.temp=Math.max(15,s.temp-28);if(d.kind==='power'){let old=p.power;p.power=Math.min(7,p.power+1);if(p.power>old){s.msg=`WEAPON UPGRADED — LV.${p.power}`;s.msgT=110}}if(d.kind==='bomb')s.bombs=Math.min(5,s.bombs+1);d.x=-100;s.score+=250}});s.drops=s.drops.filter(d=>d.x>-40)}
function spawnBoss(){s.boss=true;s.wave=-999;let n=['THE ETERNAL CLUMP','THE SEIZED GEARBOX','THE BLOOM BEAST'][s.stage-1];s.enemies.push({x:W-120,y:H/2,vx:0,vy:0,hp:80+s.stage*45,max:80+s.stage*45,r:58+s.stage*7,kind:s.stage+2,bossIndex:s.stage-1,t:0,boss:true,name:n});s.msg=`WARNING: ${n}`;s.msgT=180}
function draw(){ctx.save();let sh=s?.shake||0;ctx.translate((Math.random()-.5)*sh,(Math.random()-.5)*sh);let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#162735');g.addColorStop(1,'#081117');ctx.fillStyle=g;ctx.fillRect(-30,-30,W+60,H+60);ctx.strokeStyle='#29414b';ctx.lineWidth=2;for(let x=0;x<W;x+=80){ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x+120,H);ctx.stroke()}for(let y=80;y<H;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#0d1d25';ctx.fillRect(0,0,W,58);ctx.fillStyle='#8fa6aa';ctx.font='700 15px monospace';ctx.fillText(`SCORE ${String(s?.score||0).padStart(7,'0')}`,24,35);ctx.fillText(`BATCH 0${s?.stage||1}/03`,400,35);ctx.fillText(`BOMBS ${s?.bombs??3}`,825,35);if(s){let p=s.p;ctx.globalAlpha=p.inv>0&&Math.floor(p.inv/5)%2?.25:1;let seq=[0,1,2,1],img=craft[seq[Math.floor(s.time/8)%4]];if(img.complete)ctx.drawImage(img,p.x-58,p.y-29,116,58);ctx.globalAlpha=1;s.shots.forEach(b=>{ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()});s.enemies.forEach(drawEnemy);s.drops.forEach(d=>{ctx.fillStyle=d.kind==='cool'?'#63d7ef':d.kind==='power'?'#ffd44d':'#ef6d55';ctx.beginPath();ctx.arc(d.x,d.y,13,0,7);ctx.fill()});hud();if(s.msgT>0){ctx.fillStyle='#050c0fd1';ctx.fillRect(210,90,540,54);ctx.strokeStyle='#ddbb69';ctx.strokeRect(210,90,540,54);ctx.fillStyle='#f8e7b7';ctx.font='800 20px monospace';ctx.textAlign='center';ctx.fillText(s.msg,480,124);ctx.textAlign='left'}}ctx.restore()}
function drawEnemy(e){let image=e.boss?bossImages[e.bossIndex]:enemyImages[e.kind];if(image?.complete&&image.naturalWidth){let w,h;if(e.boss){let sizes=[[190,127],[205,137],[220,147]][e.bossIndex]||[190,127];w=sizes[0];h=sizes[1]}else{h=e.r*2.8;w=h*.75}ctx.save();ctx.translate(e.x,e.y);if(!e.boss)ctx.scale(-1,1);ctx.drawImage(image,-w/2,-h/2,w,h);ctx.restore()}else{ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.boss?'#6b3428':['#75402e','#c78d5f','#d7ddd3','#5b7c7d'][e.kind%4];ctx.strokeStyle=e.boss?'#f0c36c':'#352019';ctx.lineWidth=e.boss?6:3;ctx.beginPath();for(let i=0;i<12;i++){let a=i/12*Math.PI*2,r=e.r*(i%2?1:.78);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}if(e.boss){let heights=[127,137,147],barY=e.y-(heights[e.bossIndex]||127)/2-18;ctx.fillStyle='#1a0c09';ctx.fillRect(e.x-85,barY,170,10);ctx.fillStyle='#efb94f';ctx.fillRect(e.x-85,barY,170*e.hp/e.max,10)}}
function hud(){let x=22,y=H-58;ctx.fillStyle='#050c0fe6';ctx.fillRect(x,y,420,40);ctx.fillStyle='#d5b96e';ctx.font='700 12px monospace';ctx.fillText('TEMPERATURE',x+12,y+16);let g=ctx.createLinearGradient(x+110,0,x+395,0);g.addColorStop(0,'#63d7ef');g.addColorStop(.45,'#e4c65c');g.addColorStop(1,'#ef5b42');ctx.fillStyle='#24343a';ctx.fillRect(x+110,y+10,285,15);ctx.fillStyle=g;ctx.fillRect(x+110,y+10,285*s.temp/100,15);ctx.strokeStyle='#fff3c7';ctx.strokeRect(x+110+285*.38,y+7,285*.22,21);ctx.fillStyle='#e65c3e';ctx.font='900 18px Impact, sans-serif';ctx.fillText('TEMPER TANTRUM',470,H-30);ctx.fillStyle='#d5b96e';ctx.font='700 14px monospace';ctx.fillText(`WEAPON LV.${s.p.power}`,650,35);ctx.fillStyle='#e8b95a';ctx.font='20px monospace';ctx.fillText('♥'.repeat(Math.max(0,s.p.hp)),W-155,H-27)}
function loop(now){let dt=Math.min(2,(now-last)/16.67);last=now;if(mode==='playing')update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
